### ISSUE TITLE
Serial recovery on nRF requires a power-cycle after flashing

### ISSUE THREAD

**Issue by carlescufi** [JuulLabs-OSS/mcuboot#307] opened 2018-06-29 11:48 UTC
When using the serial recovery mode and after flashing with `ninja flash` and resetting with button 1 pressed, `mcumgr` will time out unless one power-cycles the board.

Not urgent, should not block 1.2

**Comment by carlescufi** [comment] 2018-06-29 11:48
CC @lemrey

**Comment by d3zd3z** [comment] 2018-06-29 18:43
Any idea if this can be fixed in software, or does it just have to be documented?

**Comment by carlescufi** [comment] 2018-06-29 18:46
I think it should be fixable by software because the UART works fine for things like the console. We will look into this very soon, but it's not serious enough to warrant delaying the release.

**Comment by lemrey** [comment] 2018-07-03 14:30
It is possible this was an issue with the virtual machine (VirtualBox). The issue disappeared when switching from the EHCI 2.0 USB controller to the OHCI 1.1 USB controller; I was not able to reproduce this in VMWare player.

**Comment by carlescufi** [comment] 2018-07-03 15:26
@lemrey can you please run Logic16 with pca10056 to see if the request packet is actually reaching the nRF IC?

**Comment by d3zd3z** [comment] 2019-12-02 16:38
Is this still an issue?

**Comment by carlescufi** [comment] 2019-12-02 16:43
@nvlsianpu @lemrey is this still relevant?

**Comment by d3zd3z** [comment] 2020-01-07 08:24
Closing. Please re-open if this is still an issue.

**Closed by d3zd3z** 2020-01-07 08:24 UTC
Labels: bug
